"""Make ship_data nullable

Revision ID: 1f6bfaafef3b
Revises: f0d7c506893b
Create Date: 2025-10-26 22:21:19.561237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f6bfaafef3b'
down_revision = 'f0d7c506893b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ship_placement', schema=None) as batch_op:
        batch_op.alter_column('ship_data',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ship_placement', schema=None) as batch_op:
        batch_op.alter_column('ship_data',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
